exports.tzabbrev = {
    "ACDT": {"name":  "Australian Central Daylight Saving Time", "hours": 10, "minutes": 30},
    "ACST": {"name":  "Australian Central Standard Time", "hours": 09, "minutes": 30},
    "ACT": {"name":  "Acre Time", "hours": -05},
    "ACT": {"name":  "ASEAN Common Time (proposed)", "hours": 08, "minutes": 00},
    "ACWST": {"name":  "Australian Central Western Standard Time (unofficial)", "hours": 08, "minutes": 45},
    "ADT": {"name":  "Atlantic Daylight Time", "hours": -03},
    "AEDT": {"name":  "Australian Eastern Daylight Saving Time", "hours": 11},
    "AEST": {"name":  "Australian Eastern Standard Time", "hours": 10},
    "AFT": {"name":  "Afghanistan Time", "hours": 04, "minutes": 30},
    "AKDT": {"name":  "Alaska Daylight Time", "hours": -08},
    "AKST": {"name":  "Alaska Standard Time", "hours": -09},
    "ALMT": {"name":  "Alma-Ata Time[1]", "hours": 06},
    "AMST": {"name":  "Amazon Summer Time (Brazil)[2]", "hours": -03},
    "AMT": {"name":  "Amazon Time (Brazil)[3]", "hours": -04},
    "AMT": {"name":  "Armenia Time", "hours": 04},
    "ANAT": {"name":  "Anadyr Time[4]", "hours": 12},
    "AQTT": {"name":  "Aqtobe Time[5]", "hours": 05},
    "ART": {"name":  "Argentina Time", "hours": -03},
    "AST": {"name":  "Arabia Standard Time", "hours": 03},
    "AST": {"name":  "Atlantic Standard Time", "hours": -04},
    "AWST": {"name":  "Australian Western Standard Time", "hours": 08},
    "AZOST": {"name":  "Azores Summer Time", "hours": 00},
    "AZOT": {"name":  "Azores Standard Time", "hours": -01},
    "AZT": {"name":  "Azerbaijan Time", "hours": 04},
    "BNT": {"name":  "Brunei Time", "hours": 08},
    "BIOT": {"name":  "British Indian Ocean Time", "hours": 06},
    "BIT": {"name":  "Baker Island Time", "hours": -12},
    "BOT": {"name":  "Bolivia Time", "hours": -04},
    "BRST": {"name":  "Brasília Summer Time", "hours": -02},
    "BRT": {"name":  "Brasília Time", "hours": -03},
    "BST": {"name":  "Bangladesh Standard Time", "hours": 06},
    "BST": {"name":  "Bougainville Standard Time[6]", "hours": 11},
    "BST": {"name":  "British Summer Time (British Standard Time from Mar 1968 to Oct 1971)", "hours": 01},
    "BTT": {"name":  "Bhutan Time", "hours": 06},
    "CAT": {"name":  "Central Africa Time", "hours": 02},
    "CCT": {"name":  "Cocos Islands Time", "hours": 06, "minutes": 30},
    "CDT": {"name":  "Central Daylight Time (North America)", "hours": -05},
    "CEST": {"name":  "Central European Summer Time", "hours": 02},
    "CET": {"name":  "Central European Time", "hours": 01},
    "CHADT": {"name":  "Chatham Daylight Time", "hours": 13, "minutes": 45},
    "CHAST": {"name":  "Chatham Standard Time", "hours": 12, "minutes": 45},
    "CHOT": {"name":  "Choibalsan Standard Time", "hours": 08},
    "CHOST": {"name":  "Choibalsan Summer Time", "hours": 09},
    "CHST": {"name":  "Chamorro Standard Time", "hours": 10},
    "CHUT": {"name":  "Chuuk Time", "hours": 10},
    "CIST": {"name":  "Clipperton Island Standard Time", "hours": -08},
    "CKT": {"name":  "Cook Island Time", "hours": -10},
    "CLST": {"name":  "Chile Summer Time", "hours": -03},
    "CLT": {"name":  "Chile Standard Time", "hours": -04},
    "COST": {"name":  "Colombia Summer Time", "hours": -04},
    "COT": {"name":  "Colombia Time", "hours": -05},
    "CST": {"name":  "Central Standard Time (Central America)", "hours": -06},
    "CVT": {"name":  "Cape Verde Time", "hours": -01},
    "CWST": {"name":  "Central Western Standard Time (Australia) unofficial", "hours": 08, "minutes": 45},
    "CXT": {"name":  "Christmas Island Time", "hours": 07},
    "DAVT": {"name":  "Davis Time", "hours": 07},
    "DDUT": {"name":  "Dumont d'Urville Time", "hours": 10},
    "DFT": {"name":  "AIX-specific equivalent of Central European Time[NB 1]", "hours": 01},
    "EASST": {"name":  "Easter Island Summer Time", "hours": -05},
    "EAST": {"name":  "Easter Island Standard Time", "hours": -06},
    "EAT": {"name":  "East Africa Time", "hours": 03},
    "ECT": {"name":  "Eastern Caribbean Time (does not recognise DST)", "hours": -04},
    "EDT": {"name":  "Eastern Daylight Time (North America)", "hours": -04},
    "EEST": {"name":  "Eastern European Summer Time", "hours": 03},
    "EET": {"name":  "Eastern European Time", "hours": 02},
    "EGST": {"name":  "Eastern Greenland Summer Time", "hours": 00},
    "EGT": {"name":  "Eastern Greenland Time", "hours": -01},
    "EST": {"name":  "Eastern Standard Time (North America)", "hours": -05},
    "FET": {"name":  "Further-eastern European Time", "hours": 03},
    "FJT": {"name":  "Fiji Time", "hours": 12},
    "FKST": {"name":  "Falkland Islands Summer Time", "hours": -03},
    "FKT": {"name":  "Falkland Islands Time", "hours": -04},
    "FNT": {"name":  "Fernando de Noronha Time", "hours": -02},
    "GALT": {"name":  "Galápagos Time", "hours": -06},
    "GAMT": {"name":  "Gambier Islands Time", "hours": -09},
    "GET": {"name":  "Georgia Standard Time", "hours": 04},
    "GFT": {"name":  "French Guiana Time", "hours": -03},
    "GILT": {"name":  "Gilbert Island Time", "hours": 12},
    "GIT": {"name":  "Gambier Island Time", "hours": -09},
    "GMT": {"name":  "Greenwich Mean Time", "hours": 00},
    "GST": {"name":  "South Georgia and the South Sandwich Islands Time", "hours": -02},
    "GST": {"name":  "Gulf Standard Time", "hours": 04},
    "GYT": {"name":  "Guyana Time", "hours": -04},
    "HDT": {"name":  "Hawaii–Aleutian Daylight Time", "hours": -09},
    "HAEC": {"name":  "Heure Avancée d'Europe Centrale French-language name for CEST", "hours": 02},
    "HST": {"name":  "Hawaii–Aleutian Standard Time", "hours": -10},
    "HKT": {"name":  "Hong Kong Time", "hours": 08},
    "HMT": {"name":  "Heard and McDonald Islands Time", "hours": 05},
    "HOVST": {"name":  "Hovd Summer Time (not used from 2017-present)", "hours": 08},
    "HOVT": {"name":  "Hovd Time", "hours": 07},
    "ICT": {"name":  "Indochina Time", "hours": 07},
    "IDLW": {"name":  "International Date Line West time zone", "hours": -12},
    "IDT": {"name":  "Israel Daylight Time", "hours": 03},
    "IOT": {"name":  "Indian Ocean Time", "hours": 06},
    "IRDT": {"name":  "Iran Daylight Time", "hours": 04, "minutes": 30},
    "IRKT": {"name":  "Irkutsk Time", "hours": 08},
    "IRST": {"name":  "Iran Standard Time", "hours": 03, "minutes": 30},
    "IST": {"name":  "Indian Standard Time", "hours": 05, "minutes": 30},
    "IST": {"name":  "Irish Standard Time[8]", "hours": 01},
    "IST": {"name":  "Israel Standard Time", "hours": 02},
    "JST": {"name":  "Japan Standard Time", "hours": 09},
    "KALT": {"name":  "Kaliningrad Time", "hours": 02},
    "KGT": {"name":  "Kyrgyzstan Time", "hours": 06},
    "KOST": {"name":  "Kosrae Time", "hours": 11},
    "KRAT": {"name":  "Krasnoyarsk Time", "hours": 07},
    "KST": {"name":  "Korea Standard Time", "hours": 09},
    "LHST": {"name":  "Lord Howe Standard Time", "hours": 10, "minutes": 30},
    "LHST": {"name":  "Lord Howe Summer Time", "hours": 11},
    "LINT": {"name":  "Line Islands Time", "hours": 14},
    "MAGT": {"name":  "Magadan Time", "hours": 12},
    "MART": {"name":  "Marquesas Islands Time", "hours": -09, "minutes": -30},
    "MAWT": {"name":  "Mawson Station Time", "hours": 05},
    "MDT": {"name":  "Mountain Daylight Time (North America)", "hours": -06},
    "MET": {"name":  "Middle European Time (same zone as CET)", "hours": 01},
    "MEST": {"name":  "Middle European Summer Time (same zone as CEST)", "hours": 02},
    "MHT": {"name":  "Marshall Islands Time", "hours": 12},
    "MIST": {"name":  "Macquarie Island Station Time", "hours": 11},
    "MIT": {"name":  "Marquesas Islands Time", "hours": -09, "minutes": -30},
    "MMT": {"name":  "Myanmar Standard Time", "hours": 06, "minutes": 30},
    "MSK": {"name":  "Moscow Time", "hours": 03},
    "MST": {"name":  "Malaysia Standard Time", "hours": 08},
    "MST": {"name":  "Mountain Standard Time (North America)", "hours": -07},
    "MUT": {"name":  "Mauritius Time", "hours": 04},
    "MVT": {"name":  "Maldives Time", "hours": 05},
    "MYT": {"name":  "Malaysia Time", "hours": 08},
    "NCT": {"name":  "New Caledonia Time", "hours": 11},
    "NDT": {"name":  "Newfoundland Daylight Time", "hours": -02, "minutes": -30},
    "NFT": {"name":  "Norfolk Island Time", "hours": 11},
    "NOVT": {"name":  "Novosibirsk Time [9]", "hours": 07},
    "NPT": {"name":  "Nepal Time", "hours": 05, "minutes": 45},
    "NST": {"name":  "Newfoundland Standard Time", "hours": -03, "minutes": -30},
    "NT": {"name":  "Newfoundland Time", "hours": -03, "minutes": -30},
    "NUT": {"name":  "Niue Time", "hours": -11},
    "NZDT": {"name":  "New Zealand Daylight Time", "hours": 13},
    "NZST": {"name":  "New Zealand Standard Time", "hours": 12},
    "OMST": {"name":  "Omsk Time", "hours": 06},
    "ORAT": {"name":  "Oral Time", "hours": 05},
    "PDT": {"name":  "Pacific Daylight Time (North America)", "hours": -07},
    "PET": {"name":  "Peru Time", "hours": -05},
    "PETT": {"name":  "Kamchatka Time", "hours": 12},
    "PGT": {"name":  "Papua New Guinea Time", "hours": 10},
    "PHOT": {"name":  "Phoenix Island Time", "hours": 13},
    "PHT": {"name":  "Philippine Time", "hours": 08},
    "PHST": {"name":  "Philippine Standard Time", "hours": 08},
    "PKT": {"name":  "Pakistan Standard Time", "hours": 05},
    "PMDT": {"name":  "Saint Pierre and Miquelon Daylight Time", "hours": -02},
    "PMST": {"name":  "Saint Pierre and Miquelon Standard Time", "hours": -03},
    "PONT": {"name":  "Pohnpei Standard Time", "hours": 11},
    "PST": {"name":  "Pacific Standard Time (North America)", "hours": -08},
    "PWT": {"name":  "Palau Time[10]", "hours": 09},
    "PYST": {"name":  "Paraguay Summer Time[11]", "hours": -03},
    "PYT": {"name":  "Paraguay Time[12]", "hours": -04},
    "RET": {"name":  "Réunion Time", "hours": 04},
    "ROTT": {"name":  "Rothera Research Station Time", "hours": -03},
    "SAKT": {"name":  "Sakhalin Island Time", "hours": 11},
    "SAMT": {"name":  "Samara Time", "hours": 04},
    "SAST": {"name":  "South African Standard Time", "hours": 02},
    "SBT": {"name":  "Solomon Islands Time", "hours": 11},
    "SCT": {"name":  "Seychelles Time", "hours": 04},
    "SDT": {"name":  "Samoa Daylight Time", "hours": -10},
    "SGT": {"name":  "Singapore Time", "hours": 08},
    "SLST": {"name":  "Sri Lanka Standard Time", "hours": 05, "minutes": 30},
    "SRET": {"name":  "Srednekolymsk Time", "hours": 11},
    "SRT": {"name":  "Suriname Time", "hours": -03},
    "SST": {"name":  "Samoa Standard Time", "hours": -11},
    "SST": {"name":  "Singapore Standard Time", "hours": 08},
    "SYOT": {"name":  "Showa Station Time", "hours": 03},
    "TAHT": {"name":  "Tahiti Time", "hours": -10},
    "THA": {"name":  "Thailand Standard Time", "hours": 07},
    "TFT": {"name":  "French Southern and Antarctic Time[13]", "hours": 05},
    "TJT": {"name":  "Tajikistan Time", "hours": 05},
    "TKT": {"name":  "Tokelau Time", "hours": 13},
    "TLT": {"name":  "Timor Leste Time", "hours": 09},
    "TMT": {"name":  "Turkmenistan Time", "hours": 05},
    "TRT": {"name":  "Turkey Time", "hours": 03},
    "TOT": {"name":  "Tonga Time", "hours": 13},
    "TST": {"name":  "Taiwan Standard Time", "hours": 08},
    "TVT": {"name":  "Tuvalu Time", "hours": 12},
    "ULAST": {"name":  "Ulaanbaatar Summer Time", "hours": 09},
    "ULAT": {"name":  "Ulaanbaatar Standard Time", "hours": 08},
    "UTC": {"name":  "Coordinated Universal Time", "hours": 00},
    "UYST": {"name":  "Uruguay Summer Time", "hours": -02},
    "UYT": {"name":  "Uruguay Standard Time", "hours": -03},
    "UZT": {"name":  "Uzbekistan Time", "hours": 05},
    "VET": {"name":  "Venezuelan Standard Time", "hours": -04},
    "VLAT": {"name":  "Vladivostok Time", "hours": 10},
    "VOLT": {"name":  "Volgograd Time", "hours": 03},
    "VOST": {"name":  "Vostok Station Time", "hours": 06},
    "VUT": {"name":  "Vanuatu Time", "hours": 11},
    "WAKT": {"name":  "Wake Island Time", "hours": 12},
    "WAST": {"name":  "West Africa Summer Time", "hours": 02},
    "WAT": {"name":  "West Africa Time", "hours": 01},
    "WEST": {"name":  "Western European Summer Time", "hours": 01},
    "WET": {"name":  "Western European Time", "hours": 00},
    "WIB": {"name":  "Western Indonesian Time", "hours": 07},
    "WIT": {"name":  "Eastern Indonesian Time", "hours": 09},
    "WITA": {"name":  "Central Indonesia Time", "hours": 08},
    "WGST": {"name":  "West Greenland Summer Time[14]", "hours": -02},
    "WGT": {"name":  "West Greenland Time[15]", "hours": -03},
    "WST": {"name":  "Western Standard Time", "hours": 08},
    "YAKT": {"name":  "Yakutsk Time", "hours": 09},
    "YEKT": {"name":  "Yekaterinburg Time", "hours": 05}
};
